simplesocial/accounts/urls.py
from django.urls import path,re_path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
        path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
        path('logout/',auth_views.LogoutView.as_view(),name='logout'),
        path('signup/',views.SignUp.as_view(),name='signup'),

]

simplesocial/posts/urls.py
from django.urls import re_path, path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    re_path(r'new/$', views.CreatePost.as_view(), name='create'),
    re_path(r'by/(?P<username>[-\w]+)',
            views.UserPosts.as_view(), name='for_user'),
    re_path(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)/$',
            views.PostDetail.as_view(), name='single'),
    re_path(r'delete/(?P<pk>\d+)/$', views.DeletePost.as_view(), name='delete'),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('posts/',include('posts.urls',namespace='posts')),
    path('groups/',include('groups.urls',namespace='groups'))
]

simplesocial/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8" />
    <title>Star Social</title>
    <!-- Latest compiled and minified CSS -->

    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous"
    />

    <!-- Optional theme -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
      integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
      crossorigin="anonymous"
    />

    <!-- Latest compiled and minified JavaScript -->
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
      integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
      crossorigin="anonymous"
    ></script>

    <link
      href="https://fonts.googleapis.com/css?family=Montserrat"
      rel="stylesheet"
    />

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}" />
  </head>

  <body>
    <div class="nav">
      <input type="checkbox" id="nav-check" />
      <div class="nav-header">
        <div class="nav-title">
          <a href="{% url 'home' %}"><span class="My_n">D</span></a>
        </div>
      </div>
      <div class="nav-btn">
        <label for="nav-check">
          <span></span>
          <span></span>
          <span></span>
        </label>
      </div>

      <div class="nav-links">
        {% if user.is_authenticated %}
        <a href="{% url 'posts:create' %}">Post</a>
        <a href="{% url 'groups:all' %}">Groups</a>
        <a href="{% url 'groups:create' %}">Create Group</a>

        <a href="{% url 'accounts:logout' %}">Log out</a>

        {% else %}
        <a href="{% url 'groups:all' %}">Groups</a>
        <a href="{% url 'accounts:login' %}">Log in</a>
        {% endif %}
      </div>
    </div>
    <div class="container intro">{% block content %} {% endblock %}</div>

    <canvas id="canvas"></canvas>
  </body>
</html>

simplesocial/templates/index.html
{% extends "base.html" %} {% block content %}
<div>
  <h1>Welcome!!!</h1>
  <h2>This webpage was built by <span class="My_n">D</span></h2>
  <h2>Login or Sign-up for free to get started!</h2>
</div>

{% endblock %}

simplesocial/templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>You are now logged in!</h1>
  <h2><a href="{% url 'groups:all'%}">Go to Groups</a></h2>


</div>




{% endblock %}

simplesocial/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}